[frontend]
frontend_instance ansible_host=FRONTEND_IP ansible_user=debian ansible_ssh_private_key_file=~/.ssh/meteo_gcp_key

[backend]
backend_instance ansible_host=BACKEND_IP ansible_user=debian ansible_ssh_private_key_file=~/.ssh/meteo_gcp_key

[mongodb]
mongodb_instance ansible_host=MONGODB_IP ansible_user=debian ansible_ssh_private_key_file=~/.ssh/meteo_gcp_key

[kafka_zookeeper]
kafka_zookeeper_instance ansible_host=KAFKA_ZOOKEEPER_IP ansible_user=debian ansible_ssh_private_key_file=~/.ssh/meteo_gcp_key

[weather_fetch]
weather_fetch_instance ansible_host=WEATHER_FETCH_IP ansible_user=debian ansible_ssh_private_key_file=~/.ssh/meteo_gcp_key

[collect_alert]
collect_alert_instance ansible_host=COLLECT_ALERT_IP ansible_user=debian ansible_ssh_private_key_file=~/.ssh/meteo_gcp_key

[monitoring]
monitoring_instance ansible_host=MONITORING_IP ansible_user=debian ansible_ssh_private_key_file=~/.ssh/meteo_gcp_key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
